env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@babel/eslint-parser"
rules:
  no-unused-vars: warn
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
