module.exports = [
  {
    index: 0,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/0/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 前屈是头部向前方运动；后伸是头部向后方运动；',
      '2) 请病人坐或站立；',
      '3) 关节正常活动范围：前屈0 ~ 60°，后伸0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/0/matters-2.png',
    action1: '前屈',
    action2: '后伸',
    sketchMapClass: 'joint-0',
    protractorImg: 1,
    protractorStyle: 'width: 645px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: 145, angle: 10 }, { rotate: 35, angle: 10 }],
    activeArea: [{ rotate: 90, flip: false }, { rotate: 90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [55, 65], negative: [45, 55] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['18,15', '30,25', '48,40'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 1,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/1/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左右侧屈是指头部向左右倾斜的运动；',
      '2) 请病人坐，固定脊椎防止胸腰椎侧屈；',
      '3) 关节正常活动范围：左侧屈0 ~ 50°，右侧屈0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/1/matters-2.png',
    action1: '左侧屈',
    action2: '右侧屈',
    sketchMapClass: 'joint-1',
    protractorImg: 1,
    protractorStyle: 'width: 645px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: 135, angle: 10 }, { rotate: 35, angle: 10 }],
    activeArea: [{ rotate: 90, flip: false }, { rotate: 90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [45, 55], negative: [45, 55] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['21,21', '35,35', '56,56'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 2,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/2/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 即头部向左右方向旋转；',
      '2) 请病人坐下或仰卧；',
      '3) 关节正常活动范围：左旋0 ~ 70°，右旋0 ~ 70°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/2/matters-2.png',
    action1: '左旋',
    action2: '右旋',
    sketchMapClass: 'joint-2',
    protractorImg: 1,
    protractorStyle: 'width: 645px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: 155, angle: 10 }, { rotate: 15, angle: 10 }],
    activeArea: [{ rotate: 90, flip: 'X' }, { rotate: 90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [65, 75], negative: [65, 75] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['15,15', '25,25', '40,40'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 3,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/3/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，在矢状面内向身体前上方摆动；',
      '2) 请病人躺卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 180°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/3/matters-2.png',
    action1: '屈曲',
    action2: '\n    \t\t\n    \t\t屈曲\n    \t',
    sketchMapClass: 'joint-3',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 4,
    mergeTo: 50,
    singleFor: 'positive',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 170, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [170, 180], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 4,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/4/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，在矢状面内向身体后下方摆动；',
      '2) 请病人俯卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/4/matters-2.png',
    action1: '伸展',
    action2: '\n    \t\t\n    \t\t伸展\n    \t',
    sketchMapClass: 'joint-4',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 3,
    mergeTo: 50,
    singleFor: 'negative',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 130, angle: 10 }],
    activeArea: [{ rotate: 180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [40, 50], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 5,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/5/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，在水平面内向前方及后方摆动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 135°（水平内收），0 ~ 30°（水平外展）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/5/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-5',
    protractorImg: 6,
    protractorStyle: 'width:563px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 120, angle: 15 }, { rotate: -30, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }, { rotate: 0, flip: 'Y' }],
    anticlockwise: false,
    motionRange: { positive: [120, 135], negative: [20, 30] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['40,9', '68,15', '108,24'],
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 6,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/6/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 肘关节屈曲90°，掌心朝下。前臂在矢状面向上及向下旋转；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 90°（外旋），0 ~ 90°（内旋）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/6/matters-2.png',
    action1: '内旋',
    action2: '外旋',
    sketchMapClass: 'joint-6',
    protractorImg: 7,
    protractorStyle: 'width:317px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 80, angle: 10 }, { rotate: -90, angle: 10 }],
    activeArea: [{ rotate: 0, flip: 'Y' }, { rotate: 0, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [80, 90], negative: [80, 90] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['27,27', '45,45', '72,72'],
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 7,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/7/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，在冠状面内向外侧及内侧摆动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围:0~180°(外展),0~75°(内收)；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/7/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-7',
    protractorImg: 2,
    protractorStyle: 'width: 640px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 180,
    restrictArea: [{ rotate: 335, angle: 10 }, { rotate: 90, angle: 20 }],
    activeArea: [{ rotate: 270, flip: false }, { rotate: 270, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [65, 75], negative: [160, 180] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['22,54', '38,90', '60,144'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 8,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/8/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内从0°做向后方的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 30°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/8/matters-2.png',
    action1: '后伸',
    action2: '\n    \t\t\n    \t\t后伸\n    \t',
    sketchMapClass: 'joint-8',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 11,
    mergeTo: 51,
    singleFor: 'negative',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 150, angle: 10 }],
    activeArea: [{ rotate: 180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [20, 30], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 9,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/9/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 内收是下肢向对侧肢体方向的运动；外展是下肢向离开对侧肢体方向的运动；',
      '2) 请病人仰卧，测内收时对侧下肢需伸直抬高；；',
      '3) 关节正常活动范围：内收0 ~ 20°，外展0 ~ 45°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/9/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-9',
    protractorImg: 8,
    protractorStyle: 'width:597px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -180,
    restrictArea: [{ rotate: -75, angle: 10 }, { rotate: -140, angle: 10 }],
    activeArea: [{ rotate: -90, flip: false }, { rotate: -90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [15, 25], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['6,14', '10,22', '16,36'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 10,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/10/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 内旋是使被测下肢的足向远离对侧肢体的方向运动；外旋是使被测下肢的足向对侧的方向运动；',
      '2) 请病人仰卧，膝关节屈曲90°，仰卧时，被测下肢在床边自然下垂，对侧下肢在床上呈膝立位；',
      '3) 关节正常活动范围：内旋0 ~ 45°，外旋0 ~ 45°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/10/matters-2.png',
    action1: '内旋',
    action2: '外旋',
    sketchMapClass: 'joint-10',
    protractorImg: 8,
    protractorStyle: 'width:597px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -180,
    restrictArea: [{ rotate: -50, angle: 10 }, { rotate: -140, angle: 10 }],
    activeArea: [{ rotate: -90, flip: 'X' }, { rotate: -90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [40, 50], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['14,14', '22,22', '36,36'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 11,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/11/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内做向头方向的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 120°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/11/matters-2.png',
    action1: '前屈',
    action2: '\n    \t\t\n    \t\t前屈\n    \t',
    sketchMapClass: 'joint-11',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 8,
    mergeTo: 51,
    singleFor: 'positive',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 110, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [110, 120], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 12,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/12/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 背屈是足尖从中立位向小腿前面的运动，跖屈是从中立位向小腿后面的运动；',
      '2) 请病人仰卧，膝关节屈曲，踝关节呈中立位；',
      '3) 关节正常活动范围：背屈0 ~ 20°，跖屈0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/12/matters-2.png',
    action1: '背屈',
    action2: '跖屈',
    sketchMapClass: 'joint-12',
    protractorImg: 9,
    protractorStyle: 'width:460px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -60,
    restrictArea: [{ rotate: 45, angle: 10 }, { rotate: -25, angle: 10 }],
    activeArea: [{ rotate: 30, flip: false }, { rotate: -30, flip: 'Y' }],
    anticlockwise: false,
    motionRange: { positive: [15, 25], negative: [45, 55] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['6,15', '10,25', '16,40'],
    refAxisName: 'Y',
    refAngle: 0,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 13,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/13/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 桡偏是手向桡骨方向运动；尺偏是手向尺骨方向运动；',
      '2) 请病人坐下或站立，屈肘90°，前臂旋前，腕中立位；',
      '3) 关节正常活动范围：桡偏0 ~ 25°，尺偏0 ~ 55°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/13/matters-2.png',
    action1: '桡偏',
    action2: '尺偏',
    sketchMapClass: 'joint-13',
    protractorImg: 1,
    protractorStyle: 'width: 645px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: 110, angle: 10 }, { rotate: 30, angle: 10 }],
    activeArea: [{ rotate: 90, flip: false }, { rotate: 90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [20, 30], negative: [50, 60] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['8,16', '12,28', '20,44'],
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 14,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/14/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左手掌靠近前臂屈侧和伸侧运动；',
      '2) 请病人保持左前臂不动；',
      '3) 关节正常活动范围：0 ~ 90°（掌屈），0 ~ 70°（背屈）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/14/matters-2.png',
    action1: '掌屈',
    action2: '背屈',
    sketchMapClass: 'joint-14',
    protractorImg: 10,
    protractorStyle: 'width:316px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 260, angle: 10 }, { rotate: 110, angle: 10 }],
    activeArea: [{ rotate: 180, flip: false }, { rotate: 180, flip: 'Y' }],
    anticlockwise: false,
    motionRange: { positive: [80, 90], negative: [60, 70] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['27,21', '45,35', '72,56'],
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 15,
    mattersTitle: '左膝关节前伸和后屈(初始位置屈曲90°)',
    mattersImg1: '_bm/resources/bm_rom_test_joint/15/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 屈曲是小腿在矢状面向臀部方向运动；',
      '2) 过伸是小腿在矢状面向从0°位向屈曲方向相反的运动；',
      '3) 关节正常活动范围：0 ~ 135°，过伸0 ~ 10°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/15/matters-2.png',
    action1: '前伸',
    action2: '后屈',
    sketchMapClass: 'joint-15',
    protractorImg: 11,
    protractorStyle: 'width:406px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -45,
    restrictArea: [{ rotate: -90, angle: 15 }, { rotate: 50, angle: 5 }],
    activeArea: [{ rotate: 135, flip: 'X' }, { rotate: 45, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [70, 90], negative: [30, 45] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['30,10', '45,20', '75,30'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 16,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/16/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，手掌朝上。前臂从前方向肱骨接近运动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 150°（屈曲），0°（伸展），0 ~ 10°（过伸）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/16/matters-2.png',
    action1: '屈曲',
    action2: '过伸',
    sketchMapClass: 'joint-16',
    protractorImg: 12,
    protractorStyle: 'width:480px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -180,
    restrictArea: [{ rotate: 50, angle: 10 }, { rotate: -100, angle: 5 }],
    activeArea: [{ rotate: -90, flip: false }, { rotate: -90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [140, 150], negative: [5, 10] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['45,0.1', '75,0.1', '120,0.1'],
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 17,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/17/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 旋前是拇指向内侧，手掌向下转动；旋后是拇指向外侧，手掌向上转动；',
      '2) 请病人坐，上臂置于体侧，屈肘90°；',
      '3) 关节正常活动范围：旋前0 ~ 90°，旋后0 ~ 90°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/17/matters-2.png',
    action1: '旋前',
    action2: '旋后',
    sketchMapClass: 'joint-17',
    protractorImg: 4,
    protractorStyle: 'width:640px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: -5, angle: 10 }, { rotate: 175, angle: 10 }],
    activeArea: [{ rotate: 90, flip: 'X' }, { rotate: 90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [85, 95], negative: [85, 95] },
    isPlaneMove: false,
    needBothBm: false,
    rangeTypeVals: ['27,27', '45,45', '72,72'],
    refAxisName: 'Y',
    refAngle: -90,
    axisNum: 1,
    axis: 'x'
  },
  {
    index: 18,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/18/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 背屈是足尖从中立位向小腿前面的运动，跖屈是从中立位向小腿后面的运动；',
      '2) 请病人仰卧，膝关节屈曲，踝关节呈中立位；',
      '3) 关节正常活动范围：背屈0 ~ 20°，跖屈0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/18/matters-2.png',
    action1: '背屈',
    action2: '跖屈',
    sketchMapClass: 'joint-18',
    protractorImg: 13,
    protractorStyle: 'width:460px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 60,
    restrictArea: [{ rotate: 195, angle: 10 }, { rotate: 125, angle: 10 }],
    activeArea: [{ rotate: 210, flip: 'Y' }, { rotate: 150, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [15, 25], negative: [45, 55] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Y',
    refAngle: 0,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['6,15', '10,25', '16,40']
  },
  {
    index: 19,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/19/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，在矢状面内向身体前上方摆动；',
      '2) 请病人躺卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 180°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/19/matters-2.png',
    action1: '屈曲',
    action2: '\n    \t\t\n    \t\t屈曲\n    \t',
    sketchMapClass: 'joint-19',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 20,
    mergeTo: 52,
    singleFor: 'positive',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 0, angle: 10 }],
    activeArea: [{ rotate: -180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [170, 180], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 20,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/20/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，在矢状面内向身体后下方摆动；',
      '2) 请病人俯卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 50°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/20/matters-2.png',
    action1: '伸展',
    action2: '\n    \t\t\n    \t\t伸展\n    \t',
    sketchMapClass: 'joint-20',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 19,
    mergeTo: 52,
    singleFor: 'negative',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 40, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [40, 50], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 21,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/21/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，在水平面内向前方及后方摆动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 135°（水平内收），0 ~ 30°（水平外展）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/21/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-21',
    protractorImg: 14,
    protractorStyle: 'width:561px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 45, angle: 15 }, { rotate: 200, angle: 10 }],
    activeArea: [{ rotate: 180, flip: 'Y' }, { rotate: 180, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [120, 135], negative: [20, 30] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['40,9', '68,15', '108,24']
  },
  {
    index: 22,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/22/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂外展90°，肘关节屈曲90°，掌心朝下。前臂在矢状面向上及向下旋转；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 90°（外旋），0 ~ 90°（内旋）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/22/matters-2.png',
    action1: '内旋',
    action2: '外旋',
    sketchMapClass: 'joint-22',
    protractorImg: 10,
    protractorStyle: 'width:316px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 90, angle: 10 }, { rotate: 260, angle: 10 }],
    activeArea: [{ rotate: 180, flip: false }, { rotate: 180, flip: 'Y' }],
    anticlockwise: false,
    motionRange: { positive: [80, 90], negative: [80, 90] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['27,27', '45,45', '72,72']
  },
  {
    index: 23,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/23/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，在冠状面内向外侧及内侧摆动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围:0~180°(外展),0~75°(内收)；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/23/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-23',
    protractorImg: 15,
    protractorStyle: 'width:624px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 180,
    restrictArea: [{ rotate: 195, angle: 10 }, { rotate: 70, angle: 20 }],
    activeArea: [{ rotate: 270, flip: 'X' }, { rotate: 270, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [65, 75], negative: [160, 180] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['22,54', '38,90', '60,144']
  },
  {
    index: 24,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/24/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内从0°做向后方的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 30°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/24/matters-2.png',
    action1: '后伸',
    action2: '\n    \t\t\n    \t\t后伸\n    \t',
    sketchMapClass: 'joint-24',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 27,
    mergeTo: 53,
    singleFor: 'negative',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 20, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [20, 30], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 25,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/25/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 内收是下肢向对侧肢体方向的运动；外展是下肢向离开对侧肢体方向的运动；',
      '2) 请病人仰卧，测内收时对侧下肢需伸直抬高；；',
      '3) 关节正常活动范围：内收0 ~ 20°，外展0 ~ 45°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/25/matters-2.png',
    action1: '内收',
    action2: '外展',
    sketchMapClass: 'joint-25',
    protractorImg: 8,
    protractorStyle: 'width:597px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: -180,
    restrictArea: [{ rotate: -50, angle: 10 }, { rotate: -115, angle: 10 }],
    activeArea: [{ rotate: -90, flip: 'X' }, { rotate: -90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [15, 25], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['6,14', '10,22', '16,36']
  },
  {
    index: 26,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/26/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 内旋是使被测下肢的足向远离对侧肢体的方向运动；外旋是使被测下肢的足向对侧的方向运动；',
      '2) 请病人仰卧，膝关节屈曲90°，仰卧时，被测下肢在床边自然下垂，对侧下肢在床上呈膝立位；',
      '3) 关节正常活动范围：内旋0 ~ 45°，外旋0 ~ 45°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/26/matters-2.png',
    action1: '内旋',
    action2: '外旋',
    sketchMapClass: 'joint-26',
    protractorImg: 8,
    protractorStyle: 'width:597px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: -180,
    restrictArea: [{ rotate: -50, angle: 10 }, { rotate: -140, angle: 10 }],
    activeArea: [{ rotate: -90, flip: false }, { rotate: -90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [40, 50], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['14,14', '22,22', '36,36']
  },
  {
    index: 27,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/27/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内做向头方向的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 120°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/27/matters-2.png',
    action1: '前屈',
    action2: '\n    \t\t\n    \t\t前屈\n    \t',
    sketchMapClass: 'joint-27',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 24,
    mergeTo: 53,
    singleFor: 'positive',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 60, angle: 10 }],
    activeArea: [{ rotate: 180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [110, 120], negative: [0, 0] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y'
  },
  {
    index: 28,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/28/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 桡偏是手向桡骨方向运动；尺偏是手向尺骨方向运动；',
      '2) 请病人坐下或站立，屈肘90°，前臂旋前，腕中立位；',
      '3) 关节正常活动范围：桡偏0 ~ 25°，尺偏0 ~ 55°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/28/matters-2.png',
    action1: '桡偏',
    action2: '尺偏',
    sketchMapClass: 'joint-28',
    protractorImg: 1,
    protractorStyle: 'width: 645px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: 140, angle: 10 }, { rotate: 60, angle: 10 }],
    activeArea: [{ rotate: 90, flip: 'X' }, { rotate: 90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [20, 30], negative: [50, 60] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['8,16', '12,28', '20,44']
  },
  {
    index: 29,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/29/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右手掌靠近前臂屈侧和伸侧运动；',
      '2) 请病人保持左前臂不动；',
      '3) 关节正常活动范围：0 ~ 90°（掌屈），0 ~ 70°（背屈）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/29/matters-2.png',
    action1: '掌屈',
    action2: '背屈',
    sketchMapClass: 'joint-29',
    protractorImg: 7,
    protractorStyle: 'width:317px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 60, angle: 10 }, { rotate: -90, angle: 10 }],
    activeArea: [{ rotate: 0, flip: 'Y' }, { rotate: 0, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [80, 90], negative: [60, 70] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['27,21', '45,35', '72,56']
  },
  {
    index: 30,
    mattersTitle: '右膝关节前伸和后屈(初始位置屈曲90°)',
    mattersImg1: '_bm/resources/bm_rom_test_joint/30/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 屈曲是小腿在矢状面向臀部方向运动；',
      '2) 过伸是小腿在矢状面向从0°位向屈曲方向相反的运动；',
      '3) 关节正常活动范围：0 ~ 135°，过伸0 ~ 10°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/30/matters-2.png',
    action1: '前伸',
    action2: '后屈',
    sketchMapClass: 'joint-30',
    protractorImg: 16,
    protractorStyle: 'width:414px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 45,
    restrictArea: [{ rotate: 255, angle: 15 }, { rotate: 125, angle: 5 }],
    activeArea: [{ rotate: 135, flip: false }, { rotate: -135, flip: 'Y' }],
    anticlockwise: false,
    motionRange: { positive: [70, 90], negative: [30, 45] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['30,10', '45,20', '75,30']
  },
  {
    index: 31,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/31/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，手掌朝上。前臂从前方向肱骨接近运动；',
      '2) 请病人坐下或是站立，保持上躯干不动；',
      '3) 关节正常活动范围：0 ~ 150°（屈曲），0°（伸展），0 ~ 10°（过伸）；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/31/matters-2.png',
    action1: '屈曲',
    action2: '过伸',
    sketchMapClass: 'joint-31',
    protractorImg: 17,
    protractorStyle: 'width:468px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 180,
    restrictArea: [{ rotate: 120, angle: 10 }, { rotate: 275, angle: 5 }],
    activeArea: [{ rotate: -90, flip: 'X' }, { rotate: -90, flip: false }],
    anticlockwise: true,
    motionRange: { positive: [140, 150], negative: [5, 10] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['45,0.1', '75,0.1', '120,0.1']
  },
  {
    index: 32,
    mattersTitle: '',
    mattersImg1: '_bm/resources/bm_rom_test_joint/32/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 旋前是拇指向内侧，手掌向下转动；旋后是拇指向外侧，手掌向上转动；',
      '2) 请病人坐，上臂置于体侧，屈肘90°；',
      '3) 关节正常活动范围：旋前0 ~ 90°，旋后0 ~ 90°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/32/matters-2.png',
    action1: '旋前',
    action2: '旋后',
    sketchMapClass: 'joint-32',
    protractorImg: 4,
    protractorStyle: 'width:640px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: null,
    mergeTo: null,
    singleFor: null,
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 0,
    restrictArea: [{ rotate: -5, angle: 10 }, { rotate: 175, angle: 10 }],
    activeArea: [{ rotate: 90, flip: false }, { rotate: 90, flip: 'X' }],
    anticlockwise: false,
    motionRange: { positive: [85, 95], negative: [85, 95] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'Y',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    rangeTypeVals: ['27,27', '45,45', '72,72']
  },
  {
    action1: '前屈',
    action2: '后伸',
    motionRange: { positive: [60, 60], negative: [60, 60] },
    mattersTitle: '腰椎前屈和后伸',
    rangeTypeVals: ['15,15', '25,25', '40,40'],
    whichBetter: 'A',
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    index: 33
  },
  {
    action1: '左侧屈',
    action2: '右侧屈',
    motionRange: { positive: [60, 60], negative: [60, 60] },
    mattersTitle: '腰椎左侧屈和右侧屈',
    rangeTypeVals: ['15,15', '25,25', '40,40'],
    whichBetter: 'A',
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    index: 34
  },
  {
    action1: '内旋',
    action2: '外旋',
    motionRange: { positive: [30, 30], negative: [15, 15] },
    mattersTitle: '左踝关节内旋和外旋',
    rangeTypeVals: ['6,3', '10,5', '16,8'],
    whichBetter: 'A',
    refAxisName: 'Y',
    refAngle: 0,
    axisNum: 1,
    axis: 'x',
    index: 35
  },
  {
    action1: '内旋',
    action2: '外旋',
    motionRange: { positive: [30, 30], negative: [15, 15] },
    mattersTitle: '右踝关节内旋和外旋',
    rangeTypeVals: ['6,3', '10,5', '16,8'],
    whichBetter: 'B',
    refAxisName: 'Y',
    refAngle: 0,
    axisNum: 1,
    axis: 'x',
    index: 36
  },
  null,
  null,
  null,
  {
    action1: '推动作',
    action2: '拉动作',
    motionRange: { positive: [70, 70], negative: [60, 60] },
    mattersTitle: '左手推拉动作',
    rangeTypeVals: ['18,15', '30,25', '48,40'],
    whichBetter: 'A',
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    index: 40
  },
  {
    action1: '捶提',
    action2: '捶打',
    motionRange: { positive: [80, 80], negative: [40, 40] },
    mattersTitle: '左手捶打动作',
    rangeTypeVals: ['24,9', '40,15', '64,24'],
    whichBetter: 'A',
    refAxisName: 'Y',
    refAngle: -90,
    axisNum: 1,
    axis: 'y',
    index: 41
  },
  {
    action1: '推动作',
    action2: '拉动作',
    motionRange: { positive: [80, 80], negative: [60, 60] },
    mattersTitle: '右手推拉动作',
    rangeTypeVals: ['18,15', '30,25', '48,40'],
    whichBetter: 'B',
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'x',
    index: 42
  },
  {
    action1: '捶提',
    action2: '捶打',
    motionRange: { positive: [80, 80], negative: [40, 40] },
    mattersTitle: '右手捶打动作',
    rangeTypeVals: ['24,9', '40,15', '64,24'],
    whichBetter: 'B',
    refAxisName: 'Y',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    index: 43
  },
  {
    action1: '提',
    action2: '打',
    motionRange: { positive: [], negative: [] },
    mattersTitle: '左手二维平面运动',
    rangeTypeVals: [],
    isPlaneMove: true,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    index: 44
  },
  {
    action1: '提',
    action2: '打',
    motionRange: { positive: [], negative: [] },
    mattersTitle: '右手二维平面运动',
    rangeTypeVals: [],
    isPlaneMove: true,
    refAxisName: 'Z',
    refAngle: 90,
    axisNum: 1,
    index: 45
  },
  null,
  null,
  null,
  null,
  {
    index: 50,
    mattersTitle: '和伸展',
    mattersImg1: '_bm/resources/bm_rom_test_joint/3/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 左臂伸直，在矢状面内向身体前上方摆动；',
      '2) 请病人躺卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 180°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/3/matters-2.png',
    action1: '屈曲',
    action2: '伸展',
    sketchMapClass: 'joint-3',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 4,
    mergeTo: 50,
    singleFor: 'positive',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 170, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [170, 180], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['54,15', '90,25', '144,40']
  },
  {
    index: 51,
    mattersTitle: '和后伸',
    mattersImg1: '_bm/resources/bm_rom_test_joint/11/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内做向头方向的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 120°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/11/matters-2.png',
    action1: '前屈',
    action2: '后伸',
    sketchMapClass: 'joint-11',
    protractorImg: 5,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 8,
    mergeTo: 51,
    singleFor: 'positive',
    whichBetter: 'A',
    radius: 262,
    pointerBaseRotate: -90,
    restrictArea: [{ rotate: 110, angle: 10 }],
    activeArea: [{ rotate: 0, flip: false }],
    anticlockwise: false,
    motionRange: { positive: [110, 120], negative: [20, 30] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['36,9', '60,15', '96,24']
  },
  {
    index: 52,
    mattersTitle: '和伸展',
    mattersImg1: '_bm/resources/bm_rom_test_joint/19/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 右臂伸直，在矢状面内向身体前上方摆动；',
      '2) 请病人躺卧，保持腰椎和颈椎不动；',
      '3) 关节正常活动范围：0 ~ 180°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/19/matters-2.png',
    action1: '屈曲',
    action2: '伸展',
    sketchMapClass: 'joint-19',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 20,
    mergeTo: 52,
    singleFor: 'positive',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 0, angle: 10 }],
    activeArea: [{ rotate: -180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [170, 180], negative: [40, 50] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['54,15', '90,25', '144,40']
  },
  {
    index: 53,
    mattersTitle: '和后伸',
    mattersImg1: '_bm/resources/bm_rom_test_joint/27/matters-1.gif',
    mattersPara: '',
    mattersItems: [
      '1) 下肢在矢状面内做向头方向的运动；',
      '2) 请病人躺卧，保持上肢不动；',
      '3) 关节正常活动范围：0 ~ 120°；'
    ],
    mattersImg2: '_bm/resources/bm_rom_test_joint/27/matters-2.png',
    action1: '前屈',
    action2: '后伸',
    sketchMapClass: 'joint-27',
    protractorImg: 3,
    protractorStyle: 'width:625px;',
    pointerStyle: 'height: 260px;-webkit-transform-origin:50% 255px;',
    bindTo: 24,
    mergeTo: 53,
    singleFor: 'positive',
    whichBetter: 'B',
    radius: 262,
    pointerBaseRotate: 90,
    restrictArea: [{ rotate: 60, angle: 10 }],
    activeArea: [{ rotate: 180, flip: 'Y' }],
    anticlockwise: true,
    motionRange: { positive: [110, 120], negative: [20, 30] },
    isPlaneMove: false,
    needBothBm: false,
    refAxisName: 'X',
    refAngle: 90,
    axisNum: 1,
    axis: 'y',
    rangeTypeVals: ['9,36', '60,15', '96,24']
  },
  null,
  null,
  null,
  null,
  null,
  null,
  {
    rangeTypeVals: ['20,0', '40,0', '60,0'],
    action1: '屈曲',
    action2: null,
    mattersTitle: '踏步训练（左髋、右髋）',
    motionRange: { positive: [90, 90], negative: [-90, -90] },
    needBothBm: true,
    refAxisName: 'Y',
    refAngle: 0,
    axisNum: 1,
    axis: 'y',
    index: 60
  }
]
