[consonants]
"b" = "ㅂ"
"p" = "ㅍ"
"m" = "ㅁ"
"f" = "ㅃ"
"d" = "ㄷ"
"t" = "ㅌ"
"n" = "ㄴ"
"l" = "ㄹ"
"z" = "ㅈ"
"c" = "ㅊ"
"s" = "ㅅ"
"g" = "ㄱ"
"k" = "ㅋ"
"ng" = "ㅇ"
"gw" = "ㄲ"
"kw" = "ㄸ"
"w" = "ㅆ"
"j" = "ㅉ"
"h" = "ㅎ"
"" = "ㅇ"

[vowel]
"aa" = "ㅏ"
"aai" = "ㅐ"
"a" = "ㅓ"    # not used independently
"ai" = "ㅔ"
"e" = "ㅡ"
"ei" = "ㅢ"
"i" = "ㅣ"
"o" = "ㅗ"
"oi" = "ㅚ"
"oe" = "ㅑ"
"oei" = "ㅒ"  # not used
"eo" = "ㅕ"   # not used independently
"eoi" = "ㅖ"
"u" = "ㅜ"
"ui" = "ㅟ"
"yu" = "ㅠ"
# ㅘㅙㅛㅝㅞ

[tailVowel]
"u" = "ㄹ"
"m" = "ㅁ"
"n" = "ㄴ"
"ng" = "ㅇ"
"p" = "ㅂ"
"t" = "ㄷ"
"k" = "ㄱ"
